_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
            "3":
                - 17
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.5
            "6": 4.48.2
            "8":
                - 5
            "12": 0.19.5
            "13": darwin-arm64
